language: python
python:
    - '3.6'
before_install:
    - sudo apt-get install -y portaudio19-dev
install:
    - pip install -r requirements.txt
script:
    - python setup.py test
    - python setup.py flake8
deploy:
    provider: pypi
    server: https://test.pypi.org/legacy/ # Remove for deployment to official PyPi repo
    user: jfarrelly_voysis
    password:
        secure: T1CXVzf6aJUbTevz+NiYHoNzLGoL6rLfy/QSov8B5p/HeWbeBggMebxBWVWktMkfGxgCEKFQZJzKFyETyC539tWlzpOK0rbjrOSNxJmPimJ0rBjta8IXg7xXdv90UUsbeglQHdZ8WciXneJm73H3cpR6Jk7lkWbISZzRwgwo/LQsc6j6nlPU79ekKy6NPqO+jc2Jq5k1H4LBX5jTECvZJJy3ky77IAx2ZTgaA8G0Dri2KvCvBnHJ6H3gP+nI5S7e0hyYdkidySUGDGxN/ONgmQ3NPBAJGxexQxSIduiGd/jdgmEzSyg6hPwXDsponWDNhPVC5jE0lHJcN+jZMP3dD9RNeOrTF87rxel3n5hwQ1yjN3r72NsJTP89N4uHP/7EjIapg1T8DwXA8yXkh4vdYQ6wx26SvxRTwksVQVlL9OkPgAAtuzNSLFyTtVbeK+42hsmxX8eqnum/RxtGaePgywpzMIuumVFDrkUkdrtZF3YAUAYQMZnf7PW4ZL0GBXNv19gxVxZ96yYMzuMGv6e+pJw2LHpJ3oJXP8Wf1c9MlE2HMa9esqQlsjm84mnwY90gJFTutPphcMMpIbLD1QM/YqJQI4EKvi/2iMupD875ApfxT67/jqqoLSGuIWHprWL+Uvu1Of3R4dIDXPHAwjNsHpk9UkB1ajJGYTJKZTtGp2c=
    on:
        tags: true
