language: python
python:
    - "3.6"
before_install:
    - apt-get install -y portaudio-dev
install:
    - pip install -r requirements.txt
script:
    - python setup.py test
    - python setup.py flake8
